### PR TITLE
Remove extra `=back`

### PR DESCRIPTION
**Pull request by jimvanderveen**
Hey @qjhart , just a quick fix for your excellent readme.

### CODE REVIEW

**Comment by jimvanderveen** [comment]
Ah, I see this is generated from the shell script. Digging a little more...

**Comment by jimvanderveen** [comment]
This looks like the mismatched instance.

**Comment by jimvanderveen** [comment]
Neat trick with the `: <<=cut`, by the way!

**Comment by jimvanderveen** [comment]
How are you generating the `README.pod` from `ezid`? The closest I have managed is:
`perldoc -u -F ezid >README.pod`
but most of the header levels are incorrect, and it includes all the `=pod`/`=cut` lines.

**Comment by qjhart** [comment]
@jimvanderveen  Thanks for the fix, and the polite comment, but the docs need a lot of work.   You've motivated me to at least put stubs in however, which I will do soon.  You use `podselect ezid > README.pod`, I've added a small Makefile, which I'll put an install script into as well.

Thanks!

**Pull request merged**
